apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlineop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: my-app-container
        image: sathwikagabbeta/docker-capsule-project-app:latest
        ports:
          - containerPort: 3999
        env:
         - name: MONGODB_URI
           value: "mongodb://mongodb:27017/Survey"
      - name: docker
        image: mongo:latest
        ports:
           - containerPort: 27017