version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/outpatients

  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
