---
- name: Deploy Node.js Application
  hosts: all
  become: yes
  vars:
    app_name: node-app
    app_port: 3000
    mongo_port: 27017
    repo_url: 'https://your-repo-url.git'  # URL to your Git repository
    repo_dest: '/opt/node-app'  # Path where the repo will be cloned
    node_version: '20.x'
 
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - curl
          - git
          - build-essential
        state: present
        update_cache: yes
 
    - name: Install Node.js
      become: yes
      apt:
        name: "nodejs"
        state: present
 
    - name: Install npm
      become: yes
      apt:
        name: "npm"
        state: present
 
    - name: Ensure MongoDB is installed
      apt:
        name: mongodb
        state: present
        update_cache: yes
 
    - name: Start and enable MongoDB
      service:
        name: mongodb
        state: started
        enabled: yes
 
    - name: Clone the application repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        force: yes
 
    - name: Install application dependencies
      npm:
        path: "{{ repo_dest }}"
        state: present
 
    - name: Start the Node.js application
      systemd:
        name: node-app
        state: started
        enabled: yes
        exec_start: "node {{ repo_dest }}/server.js"
        working_directory: "{{ repo_dest }}"
        user: "node"
 
    - name: Configure and restart Node.js service
      template:
        src: node-app.service.j2
        dest: /etc/systemd/system/node-app.service
      notify:
        - restart node-app
 
  handlers:
    - name: restart node-app
      systemd:
        name: node-app
        state: restarted